---
- name: read csv
  read_csv:
    path: "{{ device_csv }}"
    key: name
  register: devices
  delegate_to: localhost

- name: add devices
  netbox_device:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.value.name }}"
      device_type: "{{ item.value.device_type }}"
      device_role: "{{ item.value.device_role }}"
      site: "{{ item.value.site }}"
      serial: "{{ item.value.serial }}"
      comments: "{{ item.value.comments }}"
  loop: "{{ devices.dict|dict2items }}"
