---
- name: read csv
  read_csv:
    path: "{{ device_csv }}"
    key: name
  register: devices
  delegate_to: localhost

# Select Primary adderss
- name: elect primary addresses
  netbox_device:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.value.name }}"
      primary_ip4: "{{ item.value.primary_ip4 }}"
  loop: "{{ devices.dict|dict2items }}"
