---
# add manufacturers
- name: add manufacturers
  netbox_manufacturer:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.name }}"
  loop: "{{ manufactures }}"
  # collection module
  collections:
  - fragmentedpacket.netbox_modules
