---
# add device role
- name: add device role
  netbox_device_role:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.name }}"
      slug: "{{ item.slug }}"
      color: "{{ item.color }}"
  loop: "{{ device_roles }}"
  # collection module
  collections:
  - fragmentedpacket.netbox_modules
